"""initial migration

Revision ID: ef2c7aa56df7
Revises: 
Create Date: 2017-05-19 16:28:49.036450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2c7aa56df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number_', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone_number_'])
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=16), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number_')
    # ### end Alembic commands ###
